import type { Metadata } from "next";
import { Montserrat, Fira_Mono, Poppins, Inter } from "next/font/google";
import { MobileNav, Cursor, Header, Footer } from "@/components/ui";
import "./globals.css";

const montserrat = Montserrat({
  weight: ["300", "400", "500", "700", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  adjustFontFallback: false,
});

const inter = Inter({
  weight: ["300", "400", "500", "700", "900"],
  subsets: ["latin"],
  adjustFontFallback: false,
});

const poppins = Poppins({
  weight: ["300", "400", "500", "700", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  adjustFontFallback: false,
});

const firamono = Fira_Mono({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  adjustFontFallback: false,
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} text-sm leading-6 transition ease text-gray-700`}
      >
        <Cursor />
        <Header />
        {children}
        <MobileNav />
      </body>
    </html>
  );
}
